all:
  children:
    ibmi_systems:
      hosts:
        ibmi_dev01:
          ansible_host: "AXDES400C"
          ansible_port: 54999
          ansible_user: "FRANJPOL"
          ansible_password: "{{ ibmi_password | default(lookup('env', 'IBMI_PASSWORD')) }}"
          ansible_connection: ssh
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_ibmi
          ansible_python_interpreter: /QOpenSys/pkgs/bin/python3.9
